version: "3"
services:

    hass:
        image: homeassistant/home-assistant:0.116.4
        volumes:
            - /var/data/homeassistant/config:/config
            - /var/data/homeassistant/data:/data
        ports:
            - "8123:8123"
        restart: always
        network_mode: host

    node-red:
        image: nodered/node-red:1.2.2-12
        environment:
            - TZ=Europe/Amsterdam
        ports:
            - "1880:1880"
        volumes:
            - /var/data/node-red:/data
        restart: always

    deconz:
        image: marthoc/deconz:stable
        volumes:
            - /var/data/deconz:/root/.local/share/dresden-elektronik/deCONZ
        devices:
            - /dev/ttyACM0
        ports:
            - 8181:8080
            - 5901:5901
        privileged: true
        restart: always
        environment:
            - DECONZ_WEB_PORT=8080
            - DECONZ_DEVICE=/dev/ttyACM0
            - DECONZ_VNC_MODE=1
            - DECONZ_VNC_PORT=5901
            - DECONZ_VNC_PASSWORD=changeme